### ISSUE TITLE
计算数值和游戏显示数值不符

### ISSUE THREAD

**Issue by 0Yimeng0** [xyzkljl1/Taiwu_EffectInfo#3]
游戏版本: 0.0.35.4 测试分支
具体如下图:
https://imgse.com/i/x6JxzQ

存档文件(因存在冰清玉洁和身法加成，需进入战斗):
https://cowtransfer.com/s/c671b32a6adc4e 
或口令  sak5gm

**Comment by xyzkljl1** [comment]
![图片](https://user-images.githubusercontent.com/16500077/197113587-644e9d3b-8eba-4462-8011-5d12a97d2c21.png)

修了，茄子悄悄移除了这里的倍率
谢谢反馈和存档
